/// <reference types="vite/client" />

/**
 * `virtual:pwa-register/vue` is generated by vite-plugin-pwa at build time, so
 * its declaration has to be pulled in explicitly - a bare `types` entry in
 * tsconfig does not reach a package subpath export.
 */
/// <reference types="vite-plugin-pwa/vue" />
